# Generated by Django 4.2.16 on 2024-11-28 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("casillerosapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Cambio_contraseña", "Cambio de contraseña"),
                            ("Apertura", "Apertura de casillero"),
                            ("Cierre", "Cierre de casillero"),
                            ("Error", "Error de Apertura"),
                        ],
                        max_length=100,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("mensaje", models.TextField()),
                (
                    "casillero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="casillerosapp.casillero",
                    ),
                ),
            ],
        ),
    ]
