# Generated by Django 4.2.16 on 2024-11-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casillerosapp", "0002_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="fecha",
            field=models.DateTimeField(),
        ),
    ]
