# Generated by Django 4.2.16 on 2024-12-02 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casillerosapp", "0004_logs_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="total_time_used",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
